module web.awesome.test {
    requires com.jwebmp.webawesome;
    requires com.jwebmp.plugins.fontawesome5;

    requires org.junit.jupiter.api;
    requires com.jwebmp.core;
    requires com.jwebmp.core.base.angular.client;


    opens com.jwebmp.webawesome.test to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.accordion to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.knowndate to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.timeinput to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.components to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.avatar to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.animatedimage to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.animation to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.popup to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.badge to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.breadcrumb to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.button to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.callout to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.card to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.carousel to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.checkbox to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.colorpicker to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.copybutton to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.details to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.dialog to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.divider to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.drawer to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.formatbytes to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.formatdate to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.formatnumber to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.icon to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.imagecompare to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.comparison to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.include to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.input to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    //opens com.jwebmp.webawesome.test.menu to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.otpinput to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.pagination to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.popover to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.progressbar to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.progressring to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.qrcode to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.radio to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.range to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.rating to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.randomcontent to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.relativetime to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.select to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.skeleton to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.spinner to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.splitpanel to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.tabgroup to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.tag to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.textarea to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.tooltip to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.tree to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.waswitch to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.text to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.scroller to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.zoom to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
    opens com.jwebmp.webawesome.test.page to tools.jackson.databind, com.jwebmp.core, org.junit.platform.commons;
}
